version: '3.5'

services:
  proxy:
    image: nginx:latest
    restart: unless-stopped
    ports:
      - 3000:80
    volumes:
      - $PWD/nginx.conf:/etc/nginx/nginx.conf:ro
      - app-build:/usr/share/nginx/html:ro

  app:
    image: node:14
    restart: unless-stopped
    user: node
    volumes:
      - app-build:/usr/src/output
      - .:/usr/src/service
    environment:
      NODE_ENV: development
    working_dir: /usr/src/service
    command: yarn watch

  api-db:
    image: postgres:latest
    restart: unless-stopped
    environment:
      POSTGRES_USER: $API_DB_USER
      POSTGRES_DB: $API_DB_NAME
      POSTGRES_PASSWORD: $API_DB_PASSWORD
    volumes:
      - api-db:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "$API_DB_USER"]
      interval: 10s
      start_period: 30s

  api:
    build: $PWD/api/.
    restart: unless-stopped
    depends_on:
      api-db:
        condition: service_healthy
    environment:
      DB_HOST: api-db
      DB_USER: $API_DB_USER
      DB_PASSWORD: $API_DB_PASSWORD
      DB_NAME: $API_DB_NAME
    volumes:
      - $PWD/api/src:/usr/local/openresty/site/lualib

  # Keycloak Identity and Access Management
  keycloak-db:
    image: postgres:latest
    restart: unless-stopped
    environment:
      POSTGRES_USER: $KEYCLOAK_DB_USER
      POSTGRES_DB: $KEYCLOAK_DB_NAME
      POSTGRES_PASSWORD: $KEYCLOAK_DB_PASSWORD
    volumes:
      - keycloak-db:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "$KEYCLOAK_DB_USER"]
      interval: 10s
      start_period: 30s

  keycloak:
    image: jboss/keycloak:15.0.2
    restart: unless-stopped
    depends_on:
      keycloak-db:
        condition: service_healthy
    environment:
      DB_ADDR: keycloak-db
      DB_PASSWORD: $KEYCLOAK_DB_PASSWORD
      DB_USER: $KEYCLOAK_DB_USER
      DB_DATABASE: $KEYCLOAK_DB_NAME
      DB_VENDOR: postgres
      JDBC_PARAMS: 'connectTimeout=30'
      # KEYCLOAK_FRONTEND_URL: "http://0.0.0.0:3000/auth"
      KEYCLOAK_PASSWORD: $KEYCLOAK_PASSWORD
      KEYCLOAK_USER: $KEYCLOAK_USER
      PROXY_ADDRESS_FORWARDING: "true"

  # db_admin:
  #   image: dpage/pgadmin4:latest
  #   ports:
  #     - 5050:5050
  #   volumes:
  #     - /tmp/servers.json:/pgadmin4/servers.json
  #   environment:
  #     PGADMIN_DEFAULT_EMAIL:lapis@domain.com
  #     PGADMIN_DEFAULT_PASSWORD: SuperSecret
  #     PGADMIN_LISTEN_PORT: 5050

volumes:
  api-db:
  keycloak-db:
  app-build:
    driver: local
    driver_opts:
      type: "tmpfs"
      device: "tmpfs"
      o: "size=256m,uid=1000"
